# Generated by Django 2.2.1 on 2021-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineOpener', '0002_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='サムネイル'),
        ),
    ]
