# Generated by Django 2.2.1 on 2021-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineOpener', '0003_auto_20210911_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='thumbnail',
            field=models.ImageField(upload_to='media', verbose_name='サムネイル'),
        ),
    ]
