# Generated by Django 2.2.1 on 2021-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineOpener', '0004_auto_20210911_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
    ]
